EduHomeAspNetProject/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAspNetProject.Models
{
    public class Tag
    {
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}

EduHomeAspNetProject/Areas/AdminPanel/Controllers/TagController.cs
using EduHomeAspNetProject.DAL;
using EduHomeAspNetProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomeAspNetProject.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class TagController : Controller
    {
        private AppDbContext _context { get; }
        public TagController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Tag> tags = _context.Tags.ToList();
            return View(tags);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Tag tag)
        {

            if (ModelState.IsValid)
            {

                _context.Tags.Add(tag);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();

        }
        public ActionResult Update(int id)
        {
            Tag tag = _context.Tags.Find(id);

            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }
        [HttpPost]
        public ActionResult Update(Tag tag)
        {

            if (ModelState.IsValid)
            {

                _context.Entry(tag).State = EntityState.Modified;
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(tag);

        }

        public ActionResult Delete(int id)
        {
            Tag tag = _context.Tags.Find(id);

            if (tag == null)
            {
                return NotFound();
            }

            _context.Tags.Remove(tag);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

EduHomeAspNetProject/Areas/AdminPanel/Views/Tag/Create.cshtml
@model Tag
@{
    ViewBag.Title = "Create";
}
<div class="container" style="margin-top:80px">
    <form class="user" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly"></div>

        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextAreaFor(m => m.Name, new { @class = "form-control form-control-user" })
            @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
        </div>


        <button class="btn btn-primary btn-user btn-block">Create</button>
    </form>
</div>

EduHomeAspNetProject/Areas/AdminPanel/Views/Tag/Index.cshtml
@model List<Tag>
@{
    ViewBag.Title = "Index";
}

<div class="container" style="margin-top:80px">
    <h1 class="h3 mb-2 text-gray-800">Tag</h1>
    <div class="row">
        <div class="col-lg-12">
            <a asp-controller="Tag" asp-action="Create" class="btn btn-primary mb-4">Create</a>
        </div>
    </div>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Modifie</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int i = 0;}
                        @foreach (var item in Model)
                        {
                            i++;
                            <tr>
                                <td>@i</td>
                                <td>@item.Name</td>
                                <td>
                                    <a href="@Url.Action("Update", "Tag", new { id=item.Id})">
                                        <i class="bx-edit-alt">Edit</i>
                                    </a>

                                    <a onclick="return confirm('Are you sure?')" href="@Url.Action("Delete", "Tag", new { id=item.Id})">
                                        <i class="bx-time">Delete</i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

EduHomeAspNetProject/Areas/AdminPanel/Views/Tag/Update.cshtml
@model Tag
@{
    ViewBag.Title = "Update";
}
<form class="user" method="post" enctype="multipart/form-data" style=" margin-top: 80px; width: 30vw; margin-left: 180px;">
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextAreaFor(m => m.Name, new { @class = "form-control form-control-user" })
        @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
    </div>
    <button class="btn btn-primary btn-user btn-block">Update</button>
</form>